apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiagent
  namespace: aiagent
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
  labels:
    app: aiagent
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aiagent
                port:
                  number: 80
